/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BEU.Curso;
import BEU.Estudiante;
import BLL.GestionCursos;
import BLL.GestionEstudiante;
import BLL.GestionMatricula;
import Garcia.Util;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistroMatricula extends javax.swing.JInternalFrame {

    private final String titulo = "Registro de matrícula";
    //Servicio //Bussiness logic layer
    private GestionCursos cursosBLL = new GestionCursos();
    private GestionEstudiante estudiantesBLL = new GestionEstudiante();
    private GestionMatricula matriculaBLL = new GestionMatricula();
    private List<Curso> cursos;
    private List<Estudiante> estudiantes;

    private boolean Validar() {
        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        if (cr.getTitulo().equals("--Seleccione--")) {
            vtnPrincipal.verMensaje("Curso no válido", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        if (est.getNombre().equals("--Seleccione--")) {
            vtnPrincipal.verMensaje("Estudiante no válido", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void CrearMatricula() throws IOException {

        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        Estudiante est = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        matriculaBLL.crear();
        matriculaBLL.configurar(cr, est);
        matriculaBLL.archivar();

    }

    private void leerCursos() {
        try {
            Curso ficticio = new Curso("--Seleccione--", "", 0.0f);
            this.cmbCursos.addItem(ficticio);
            cursos = cursosBLL.getCursos();
            //Expresion lambda
            cursos.forEach((c) -> {
                this.cmbCursos.addItem(c);
            });

        } catch (Exception e) {
            vtnPrincipal.verMensaje("Error al leer los cursos", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void leerEstudiantes() {
        try {

            Estudiante ficticio = new Estudiante();
            ficticio.setNombre("--Seleccione--");
            ficticio.setApellido("");
            this.cmbEstudiantes.addItem(ficticio);

            estudiantes = estudiantesBLL.leerEstudiantes();
            //Expresion lambda
            estudiantes.forEach((est) -> {
                this.cmbEstudiantes.addItem(est);
            });

        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString());
            vtnPrincipal.verMensaje("Error al leer los estudiantes", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form frmRegistroMatricula
     */
    public frmRegistroMatricula() {
        initComponents();
        leerCursos();
        leerEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroMatricula = new javax.swing.JPanel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        cmbEstudiantes = new javax.swing.JComboBox<>();
        cmbCursos = new javax.swing.JComboBox<>();
        lblRegistroMatricula = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de matrículas");

        pnlRegistroMatricula.setBackground(new java.awt.Color(204, 204, 255));

        lblEstudiante.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblEstudiante.setText("Estudiante:");

        lblCurso.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        lblCurso.setText("Curso:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroMatriculaLayout = new javax.swing.GroupLayout(pnlRegistroMatricula);
        pnlRegistroMatricula.setLayout(pnlRegistroMatriculaLayout);
        pnlRegistroMatriculaLayout.setHorizontalGroup(
            pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroMatriculaLayout.createSequentialGroup()
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistroMatriculaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistroMatriculaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstudiante)
                            .addComponent(lblCurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstudiantes, 0, 590, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        pnlRegistroMatriculaLayout.setVerticalGroup(
            pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroMatriculaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstudiante)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        lblRegistroMatricula.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblRegistroMatricula.setText("Registro de matrícula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(lblRegistroMatricula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblRegistroMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRegistroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (Validar()) {
            CrearMatricula();
            vtnPrincipal.verMensaje("Matrícula creada correctamente", titulo, JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            Util.imprimir("Error: " + e.toString());
            vtnPrincipal.verMensaje("Error al crear la matrícula", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JComboBox<Estudiante> cmbEstudiantes;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblRegistroMatricula;
    private javax.swing.JPanel pnlRegistroMatricula;
    // End of variables declaration//GEN-END:variables
}
